"""add is_available to doctor_hospitals

Revision ID: e056bcbcad1e
Revises: d05c9670d579
Create Date: 2026-07-07 17:29:38.420836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e056bcbcad1e'
down_revision: Union[str, Sequence[str], None] = 'd05c9670d579'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor_hospitals', sa.Column('is_available', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctor_hospitals', 'is_available')
    # ### end Alembic commands ###
